language: python
python:
  - "3.6"
  - "3.7"
  - "3.7-dev"
  - "3.8-dev"
  - "nightly"

install:
  - python -m pip || wget -qO- https://bootstrap.pypa.io/get-pip.py | python
  - pip install coverage
  - pip install codecov
  - pip install wheel
  - pip install -e .
  - pip install docutils

script:
  - cd tests
  - coverage run test_all.py
  - codecov
